In [2]:
dataset_id = "faers_staging"
!bq --location=US mk --dataset {dataset_id}

BigQuery error in mk operation: Dataset 'studied-brand-266702:faers_staging'
already exists.

In [11]:
!bq --location=US load --autodetect --skip_leading_rows=1 \
--source_format=CSV {dataset_id}.Demographic 'gs://cs327e_project_data/drug_data/demo2018q4.csv' \
primaryid:INT64,caseid:INT64,caseversion:INT64,i_f_code:STRING,i_f_code_num:INT64,event_dt:INT64,\
event_dt_num:DATE,mfr_dt:INT64,mfr_dt_num:DATE,init_fda_dt:INT64,init_fda_dt_num:DATE,fda_dt:INT64,fda_dt_num:DATE,\
rept_cod:STRING,rept_cod_num:INT64,auth_num:STRING,mfr_num:STRING,mfr_sndr:STRING,lit_ref:STRING,age:INT64,\
age_cod:STRING,age_grp:STRING,age_grp_num:STRING,sex:STRING,e_sub:STRING,wt:FLOAT64,wt_cod:STRING,rept_dt:INT64,\
rept_dt_num:DATE,to_mfr:STRING,occp_cod:STRING,reporter_country:STRING,occr_country:STRING,occp_cod_num:INT64

Waiting on bqjob_r2532c14fcac861be_0000017190f5880c_1 ... (23s) Current status: DONE

In [5]:
!bq --location=US load --autodetect --skip_leading_rows=1 \
--source_format=CSV {dataset_id}.Drug 'gs://cs327e_project_data/drug_data/drug2018q4.csv'

Waiting on bqjob_r1ccae2bfffbfc1fb_0000017184b77537_1 ... (48s) Current status: DONE

In [6]:
!bq --location=US load --autodetect --skip_leading_rows=1 \
--source_format=CSV {dataset_id}.Reaction 'gs://cs327e_project_data/drug_data/reac2018q4.csv'

Waiting on bqjob_r76940ffa36ff7c58_0000017184b848fe_1 ... (6s) Current status: DONE

### View sample records from each dataset

In [13]:
# Remove limit on number of columns shown
import pandas as pd
pd.set_option('display.max_columns', None)

In [14]:
%%bigquery
select * from faers_staging.Demographic
limit 5
# View sample records of demographic table

,primaryid,caseid,caseversion,i_f_code,i_f_code_num,event_dt,event_dt_num,mfr_dt,mfr_dt_num,init_fda_dt,init_fda_dt_num,fda_dt,fda_dt_num,rept_cod,rept_cod_num,auth_num,mfr_num,mfr_sndr,lit_ref,age,age_cod,age_grp,age_grp_num,sex,e_sub,wt,wt_cod,rept_dt,rept_dt_num,to_mfr,occp_cod,reporter_country,occr_country,occp_cod_num
0,151278151,15127815,1,I,72,20170815.0,2017-08-15,20170817,2017-08-17,20180710,2018-07-10,20180710,2018-07-10,PER,806982,None,US-LYNE LABORATORIES INC.-2051690,LYNE LABORATORIES,None,72.0,YR,None,None,F,Y,None,None,20180710,2018-07-10,None,None,US,US,None
1,151320861,15132086,1,I,72,NaN,None,20180710,2018-07-10,20180711,2018-07-11,20180711,2018-07-11,PER,806982,None,US-LEADING PHARMA-2051815,LEADING PHARMA,NOT APPLICABLE,NaN,None,None,None,M,Y,None,None,20180711,2018-07-11,None,None,US,US,None
2,151321461,15132146,1,I,72,2016.0,2016-07-02,20180212,2018-02-12,20180711,2018-07-11,20180711,2018-07-11,PER,806982,None,"US-CEDIPROF, INC.-2051817",CEDIPROF,None,NaN,None,None,None,None,Y,None,None,20180711,2018-07-11,None,None,US,US,None
3,151321511,15132151,1,I,72,NaN,None,20170501,2017-05-01,20180711,2018-07-11,20180711,2018-07-11,PER,806982,None,"US-CEDIPROF, INC.-2051818",CEDIPROF,None,NaN,None,None,None,F,Y,None,None,20180711,2018-07-11,None,None,US,US,None
4,151321541,15132154,1,I,72,NaN,None,20170504,2017-05-04,20180711,2018-07-11,20180711,2018-07-11,PER,806982,None,"US-CEDIPROF, INC.-2051819",CEDIPROF,None,NaN,None,None,None,F,Y,None,None,20180711,2018-07-11,None,None,US,US,None

In [17]:
%%bigquery
select distinct mfr_sndr from faers_staging.Demographic
# View unique drug manufacturers

                              mfr_sndr
0                    LYNE LABORATORIES
1                       LEADING PHARMA
2                             CEDIPROF
3                                LUPIN
4                            DUCHESNAY
..                                 ...
467                       UMEDICA LABS
468           TAMARANG PHARMACEUTICALS
469                             EMCURE
470                              GALEN
471  PHARMA RESEARCH SOFTWARE SOLUTION

[472 rows x 1 columns]

In [15]:
%%bigquery
select * from faers_staging.Drug
limit 5
# View sample records of drug table

,primaryid,caseid,drug_seq,role_cod,drugname,prod_ai,val_vbm,route,dose_vbm,cum_dose_chr,cum_dose_unit,dechal,rechal,lot_num,exp_dt,exp_dtstr,exp_dt_mult,nda_num,dose_amt,dose_unit,dose_form,dose_freq
0,40465654,4046565,3,C,ANTIHEMOPHILIC FACTOR,"ANTIHEMOPHILIC FACTOR, HUMAN RECOMBINANT",1,Intravenous (not otherwise specified),DRUG: BAXTERVREKOMBINAT.,NaN,None,None,None,None,None,None,0,None,2000.000,IU,None,/wk
1,58030615,5803061,4,C,TAXOTERE,DOCETAXEL,1,Intravenous drip,"35 MG/M2, QW",665.0,MG/M2,N,None,None,None,None,0,None,35.000,MG/M**2,SOLUTION FOR INFUSION,/wk
2,58459643,5845964,4,C,DIGOXIN.,DIGOXIN,1,Unknown,"0.125 MG, QD",NaN,None,D,None,None,None,None,0,None,0.125,MG,None,QD
3,58459643,5845964,5,C,DIGOXIN.,DIGOXIN,1,Unknown,"0.13 MG, UNK",NaN,None,D,None,None,None,None,0,None,0.130,MG,None,None
4,58459643,5845964,9,C,PREDNISOLONE.,PREDNISOLONE,1,Unknown,"7.5 MG, QD",NaN,None,D,None,None,None,None,0,None,7.500,MG,None,QD

In [16]:
%%bigquery
select * from faers_staging.Reaction
limit 5
# View sample records of reaction table

   primaryid   caseid                       pt             drug_rec_act
0   64242818  6424281                   Oedema                   Oedema
1   75498422  7549842   Hepatic encephalopathy   Hepatic encephalopathy
2   80119642  8011964  Dermatitis psoriasiform  Dermatitis psoriasiform
3   93112092  9311209       Pulmonary embolism       Pulmonary embolism
4   98287512  9828751           Conjunctivitis           Conjunctivitis